{
 "title": "EcoLinker - Live",
 "description": "EcoFlow live dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(ecolinker_ecoflow_mqtt_enabled,job)"
    }
   },
   {
    "name": "device",
    "label": "Device",
    "query": {
     "query": "label_values(ecolinker_ecoflow_mqtt_message_last_received{job=\"$job\"},device)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "ecolinker_mpptPwr{job=\"$job\",device=\"$device\"}",
     "legendFormat": "Solar generation"
    },
    {
     "expr": "ecolinker_bpPwr{job=\"$job\",device=\"$device\"}",
     "legendFormat": "Battery charge/discharge"
    },
    {
     "expr": "ecolinker_sysLoadPwr{job=\"$job\",device=\"$device\"}",
     "legendFormat": "Household consumption"
    },
    {
     "expr": "ecolinker_sysGridPwr{job=\"$job\",device=\"$device\"}",
     "legendFormat": "Grid import/export"
    }
   ]
  },
  {
   "title": "Battery Level",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "ecolinker_bpSoc{job=\"$job\",device=\"$device\"}",
     "legendFormat": "Battery Level"
    }
   ]
  },
  {
   "title": "Maximum Power Point Tracking (MPPT)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 }
  },
  {
   "title": "Solar power",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "ecolinker_mpptHeartBeat_mpptPv_pwr{job=\"$job\",device=\"$device\"}",
     "legendFormat": "Watts ({{index0}}, {{index1}})"
    }
   ]
  },
  {
   "title": "Solar voltage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "ecolinker_mpptHeartBeat_mpptPv_vol{job=\"$job\",device=\"$device\"}",
     "legendFormat": "Volts in ({{index0}}, {{index1}})"
    }
   ]
  },
  {
   "title": "Solar current",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "expr": "ecolinker_mpptHeartBeat_mpptPv_amp{job=\"$job\",device=\"$device\"}",
     "legendFormat": "Amp in ({{index0}}, {{index1}})"
    }
   ]
  },
  {
   "title": "3 Phases (L1, L2, L3)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Power",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 8, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "ecolinker_pcsAPhase_actPwr{job=\"$job\",device=\"$device\"}",
       "legendFormat": "Phase A"
      },
      {
       "expr": "ecolinker_pcsBPhase_actPwr{job=\"$job\",device=\"$device\"}",
       "legendFormat": "Phase B"
      },
      {
       "expr": "ecolinker_pcsCPhase_actPwr{job=\"$job\",device=\"$device\"}",
       "legendFormat": "Phase C"
      }
     ]
    },
    {
     "title": "Apprarent Power",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 8, "x": 8, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "ecolinker_pcsAPhase_apparentPwr{job=\"$job\",device=\"$device\"}",
       "legendFormat": "Phase A"
      },
      {
       "expr": "ecolinker_pcsBPhase_apparentPwr{job=\"$job\",device=\"$device\"}",
       "legendFormat": "Phase B"
      },
      {
       "expr": "ecolinker_pcsCPhase_apparentPwr{job=\"$job\",device=\"$device\"}",
       "legendFormat": "Phase C"
      }
     ]
    },
    {
     "title": "Reactive Power",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 8, "x": 16, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "ecolinker_pcsAPhase_reactPwr{job=\"$job\",device=\"$device\"}",
       "legendFormat": "Phase A"
      },
      {
       "expr": "ecolinker_pcsBPhase_reactPwr{job=\"$job\",device=\"$device\"}",
       "legendFormat": "Phase B"
      },
      {
       "expr": "ecolinker_pcsCPhase_reactPwr{job=\"$job\",device=\"$device\"}",
       "legendFormat": "Phase C"
      }
     ]
    },
    {
     "title": "Power Factor (Efficiency)",
     "type": "timeseries",
     "description": "The power factor tells you how much of the supplied power is being used effectively. A value close to 1 (or -1) is ideal; a value much less than 1 means inefficiency.\n\nThe negative sign indicates the direction of power flow (possibly exporting power to the grid or reverse flow).\n\nThe magnitude shows that the apparent power is being used for useful work.",
     "gridPos": { "h": 14, "w": 8, "x": 0, "y": 66 },
     "targets": [
      {
       "expr": "ecolinker_pcsAPhase_actPwr{job=\"$job\",device=\"$device\"}/ecolinker_pcsAPhase_apparentPwr{job=\"$job\",device=\"$device\"}",
       "legendFormat": "Phase A"
      },
      {
       "expr": "ecolinker_pcsBPhase_actPwr{job=\"$job\",device=\"$device\"}/ecolinker_pcsBPhase_apparentPwr{job=\"$job\",device=\"$device\"}",
       "legendFormat": "Phase B"
      },
      {
       "expr": "ecolinker_pcsCPhase_actPwr{job=\"$job\",device=\"$device\"}/ecolinker_pcsCPhase_apparentPwr{job=\"$job\",device=\"$device\"}",
       "legendFormat": "Phase C"
      }
     ]
    },
    {
     "title": "Voltage",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 8, "x": 8, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "expr": "ecolinker_pcsAPhase_vol{job=\"$job\",device=\"$device\"}",
       "legendFormat": "Phase A"
      },
      {
       "expr": "ecolinker_pcsBPhase_vol{job=\"$job\",device=\"$device\"}",
       "legendFormat": "Phase B"
      },
      {
       "expr": "ecolinker_pcsCPhase_vol{job=\"$job\",device=\"$device\"}",
       "legendFormat": "Phase C"
      }
     ]
    },
    {
     "title": "Current",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 8, "x": 16, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "targets": [
      {
       "expr": "ecolinker_pcsAPhase_amp{job=\"$job\",device=\"$device\"}",
       "legendFormat": "Phase A"
      },
      {
       "expr": "ecolinker_pcsBPhase_amp{job=\"$job\",device=\"$device\"}",
       "legendFormat": "Phase B"
      },
      {
       "expr": "ecolinker_pcsCPhase_amp{job=\"$job\",device=\"$device\"}",
       "legendFormat": "Phase C"
      }
     ]
    },
    {
     "title": "Import / Export",
     "type": "timeseries",
     "description": "This gives you the net energy flow (kWh) over the past hour.\n\nPositive value: Net import from grid.\nNegative value: Net export to grid.\n\n0.0083333333 = 30s scraping time.",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "targets": [
      {
       "expr": "(\n  sum_over_time(ecolinker_pcsAPhase_actPwr{job=\"$job\",device=\"$device\"}[1h])\n  +\n  sum_over_time(ecolinker_pcsBPhase_actPwr{job=\"$job\",device=\"$device\"}[1h])\n  +\n  sum_over_time(ecolinker_pcsCPhase_actPwr{job=\"$job\",device=\"$device\"}[1h])\n) * 0.0083333333 / 1000",
       "legendFormat": "over last 1h"
      },
      {
       "expr": "(\n  sum_over_time(ecolinker_pcsAPhase_actPwr{job=\"$job\",device=\"$device\"}[6h])\n  +\n  sum_over_time(ecolinker_pcsBPhase_actPwr{job=\"$job\",device=\"$device\"}[6h])\n  +\n  sum_over_time(ecolinker_pcsCPhase_actPwr{job=\"$job\",device=\"$device\"}[6h])\n) * 0.0083333333 / 1000",
       "legendFormat": "over last 6h"
      },
      {
       "expr": "(\n  sum_over_time(ecolinker_pcsAPhase_actPwr{job=\"$job\",device=\"$device\"}[1d])\n  +\n  sum_over_time(ecolinker_pcsBPhase_actPwr{job=\"$job\",device=\"$device\"}[1d])\n  +\n  sum_over_time(ecolinker_pcsCPhase_actPwr{job=\"$job\",device=\"$device\"}[1d])\n) * 0.0083333333 / 1000",
       "legendFormat": "over last 1d"
      },
      {
       "expr": "(\n  sum_over_time(ecolinker_pcsAPhase_actPwr{job=\"$job\",device=\"$device\"}[2d])\n  +\n  sum_over_time(ecolinker_pcsBPhase_actPwr{job=\"$job\",device=\"$device\"}[2d])\n  +\n  sum_over_time(ecolinker_pcsCPhase_actPwr{job=\"$job\",device=\"$device\"}[2d])\n) * 0.0083333333 / 1000",
       "legendFormat": "over last 2d"
      },
      {
       "expr": "(\n  sum_over_time(ecolinker_pcsAPhase_actPwr{job=\"$job\",device=\"$device\"}[7d])\n  +\n  sum_over_time(ecolinker_pcsBPhase_actPwr{job=\"$job\",device=\"$device\"}[7d])\n  +\n  sum_over_time(ecolinker_pcsCPhase_actPwr{job=\"$job\",device=\"$device\"}[7d])\n) * 0.0083333333 / 1000",
       "legendFormat": "over last 7d"
      },
      {
       "expr": "(\n  sum_over_time(ecolinker_pcsAPhase_actPwr{job=\"$job\",device=\"$device\"}[30d])\n  +\n  sum_over_time(ecolinker_pcsBPhase_actPwr{job=\"$job\",device=\"$device\"}[30d])\n  +\n  sum_over_time(ecolinker_pcsCPhase_actPwr{job=\"$job\",device=\"$device\"}[30d])\n) * 0.0083333333 / 1000",
       "legendFormat": "over last 30d"
      }
     ]
    }
   ]
  },
  {
   "title": "MQTT",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "EcoFlow Enabled",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 170 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ecolinker_ecoflow_mqtt_enabled{job=\"$job\"}"
      }
     ]
    },
    {
     "title": "EcoFlow Connected",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 170 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ecolinker_ecoflow_mqtt_connected{job=\"$job\"}"
      }
     ]
    },
    {
     "title": "Forward Enabled",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 170 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ecolinker_mqtt_forward_enabled{job=\"$job\"}"
      }
     ]
    },
    {
     "title": "Forward Connected",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 170 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ecolinker_mqtt_forward_connected{job=\"$job\"}"
      }
     ]
    },
    {
     "title": "Messages processed",
     "type": "stat",
     "description": "Processed messages since last restart",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 170 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ecolinker_ecoflow_mqtt_messages_received{job=\"$job\", device=\"$device\"}"
      }
     ]
    },
    {
     "title": "Last Message Received",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 170 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "timestamp(round(ecolinker_ecoflow_mqtt_message_last_received{job=\"$job\",device=\"$device\"}, 1)) * 1000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "MQTT Messages Per Second",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 174 },
     "fieldConfig": { "defaults": { "unit": "m/s" } },
     "targets": [
      {
       "expr": "rate(ecolinker_ecoflow_mqtt_messages_received{job=\"$job\",device=\"$device\"}[10m])",
       "legendFormat": "MQTT Messages"
      }
     ]
    }
   ]
  },
  {
   "title": "Collectors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "Invocations",
     "type": "stat",
     "description": "Collector invocations since last restart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 185 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ecolinker_collector_invocations{job=\"$job\", device=\"$device\"}",
       "legendFormat": "{{kind}} ({{id}})"
      }
     ]
    },
    {
     "title": "Last Invocation",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 185 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "round(ecolinker_collector_last_invocation{job=\"$job\",device=\"$device\"}, 1) * 1000",
       "legendFormat": "{{kind}} ({{id}})"
      }
     ]
    },
    {
     "title": "Invocations Per Second",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 193 },
     "fieldConfig": { "defaults": { "unit": "m/s" } },
     "targets": [
      {
       "expr": "rate(ecolinker_collector_invocations{job=\"$job\",device=\"$device\"}[10m])",
       "legendFormat": "{{kind}} ({{id}})"
      }
     ]
    }
   ]
  },
  {
   "title": "EcoLinker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Count per status code",
     "type": "stat",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 588 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "promhttp_metric_handler_requests_total{job=\"$job\"}",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "Request Total",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 15, "x": 9, "y": 588 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(requests_total{job=\"$job\"})",
       "legendFormat": "{{code}} | {{method}} | {{path}}"
      }
     ]
    },
    {
     "title": "Sum Request Size",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 596 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "request_size_bytes_sum{job=\"$job\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Sum Response Size",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 596 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "response_size_bytes_sum{job=\"$job\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Requests in flight",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 596 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "promhttp_metric_handler_requests_in_flight{job=\"$job\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Request Duration Count",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 15, "x": 9, "y": 596 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(request_duration_count{job=\"$job\"})",
       "legendFormat": "{{method}} | {{path}}"
      }
     ]
    },
    {
     "title": "Avg. Size / Request",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 600 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(request_size_bytes_sum{job=\"$job\"})/request_size_bytes_count{job=\"$job\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Avg. Size / Response",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 600 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(response_size_bytes_sum{job=\"$job\"})/response_size_bytes_count{job=\"$job\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Requests with error",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 600 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "promhttp_metric_handler_errors_total{job=\"$job\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Used Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 604 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "go_memstats_sys_bytes{job=\"$job\"}"
      }
     ]
    },
    {
     "title": "Memory in Off-Heap",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 612 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "go_memstats_mspan_inuse_bytes{job=\"$job\"}"
      },
      {
       "expr": "go_memstats_mspan_sys_bytes{job=\"$job\"}"
      },
      {
       "expr": "go_memstats_mcache_inuse_bytes{job=\"$job\"}"
      },
      {
       "expr": "go_memstats_mcache_sys_bytes{job=\"$job\"}"
      },
      {
       "expr": "go_memstats_buck_hash_sys_bytes{job=\"$job\"}"
      },
      {
       "expr": "go_memstats_gc_sys_bytes{job=\"$job\"}"
      },
      {
       "expr": "go_memstats_other_sys_bytes{job=\"$job\"} - go_memstats_other_sys_bytes{job=\"$job\"}",
       "legendFormat": "bytes of memory are used for other runtime allocations {instance={{instance}}}"
      },
      {
       "expr": "go_memstats_next_gc_bytes{job=\"$job\"}"
      }
     ]
    },
    {
     "title": "Memory in Heap",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 612 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "go_memstats_heap_alloc_bytes{job=\"$job\"}"
      },
      {
       "expr": "go_memstats_heap_sys_bytes{job=\"$job\"}"
      },
      {
       "expr": "go_memstats_heap_idle_bytes{job=\"$job\"}"
      },
      {
       "expr": "go_memstats_heap_inuse_bytes{job=\"$job\"}"
      },
      {
       "expr": "go_memstats_heap_released_bytes{job=\"$job\"}"
      }
     ]
    },
    {
     "title": "Memory in Stack",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 620 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "go_memstats_stack_inuse_bytes{job=\"$job\"}"
      },
      {
       "expr": "go_memstats_stack_sys_bytes{job=\"$job\"}"
      }
     ]
    },
    {
     "title": "Rate of Objects Allocated",
     "type": "timeseries",
     "description": "shows how many heap objects are allocated. This is a counter value so you can use rate() to objects allocated/s.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 620 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(go_memstats_mallocs_total{job=\"$job\"}[10m])"
      }
     ]
    },
    {
     "title": "Number of Live Objects",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 628 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "go_memstats_mallocs_total{job=\"$job\"} - go_memstats_frees_total{job=\"$job\"}"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 628 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "go_goroutines{job=\"$job\"}"
      }
     ]
    },
    {
     "title": "Rate of a Pointer Dereferences",
     "type": "timeseries",
     "description": "go_memstats_lookups_total – counts how many pointer dereferences happened. This is a counter value so you can use rate() to lookups/s.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 636 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(go_memstats_lookups_total{job=\"$job\"}[10m])"
      }
     ]
    },
    {
     "title": "GC duration quantile",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 636 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "go_gc_duration_seconds{job=\"$job\"}"
      }
     ]
    },
    {
     "title": "Rates of Allocation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 644 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(go_memstats_alloc_bytes_total{job=\"$job\"}[10m])"
      }
     ]
    }
   ]
  }
 ]
}